name: Actions Demo
run-name: Gloria is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:  
      - name: checkout
        uses: actions/checkout@v4
      - run: npm install
      - run: npm run check-types
      - run: npm run lint
      - run: npm run test
      - run: echo "ğŸ This job's status is ${{ job.status }}."